// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cosine_distance
double cosine_distance(NumericVector x, NumericVector y);
RcppExport SEXP _pathway_cosine_distance(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cosine_distance(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rowwise_cosine_dist
NumericVector rowwise_cosine_dist(NumericMatrix x, int a);
RcppExport SEXP _pathway_rowwise_cosine_dist(SEXP xSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(rowwise_cosine_dist(x, a));
    return rcpp_result_gen;
END_RCPP
}
// cos_midpoint
int cos_midpoint(NumericMatrix x, int a, int b);
RcppExport SEXP _pathway_cos_midpoint(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(cos_midpoint(x, a, b));
    return rcpp_result_gen;
END_RCPP
}
// midpoint
int midpoint(NumericMatrix x, int a, int b);
RcppExport SEXP _pathway_midpoint(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(midpoint(x, a, b));
    return rcpp_result_gen;
END_RCPP
}
// cpath
IntegerVector cpath(NumericMatrix x, int a, int b);
RcppExport SEXP _pathway_cpath(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(cpath(x, a, b));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _pathway_full_matrix_cosine_distance(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_pathway_cosine_distance", (DL_FUNC) &_pathway_cosine_distance, 2},
    {"_pathway_rowwise_cosine_dist", (DL_FUNC) &_pathway_rowwise_cosine_dist, 2},
    {"_pathway_cos_midpoint", (DL_FUNC) &_pathway_cos_midpoint, 3},
    {"_pathway_midpoint", (DL_FUNC) &_pathway_midpoint, 3},
    {"_pathway_cpath", (DL_FUNC) &_pathway_cpath, 3},
    {"_pathway_full_matrix_cosine_distance", (DL_FUNC) &_pathway_full_matrix_cosine_distance, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_pathway(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
