# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cosine_distance <- function(x, y) {
    .Call('_pathway_cosine_distance', PACKAGE = 'pathway', x, y)
}

rowwise_cosine_dist <- function(x, a) {
    .Call('_pathway_rowwise_cosine_dist', PACKAGE = 'pathway', x, a)
}

cos_midpoint <- function(x, a, b) {
    .Call('_pathway_cos_midpoint', PACKAGE = 'pathway', x, a, b)
}

midpoint <- function(x, a, b) {
    .Call('_pathway_midpoint', PACKAGE = 'pathway', x, a, b)
}

cpath <- function(x, a, b) {
    .Call('_pathway_cpath', PACKAGE = 'pathway', x, a, b)
}

